### ISSUE TITLE
Need an autoscroll

### ISSUE THREAD

**Issue by benjaminbra** [benjaminbra/chat-socket#4]
When a new message is send and a conversation is long enough, we can see that is not autoscroll to the new messages.

Maybe, when the user is on the last message, and then when there is a new message, there is an autoscroll.

And if the user is not on the last message, then the autoscroll stop to work.

**Comment by pierrerispal** [comment]
or maybe you can reverse the whole things, new messages and connections are shown above previous ones so that the last message send is on top on everything
