### ISSUE TITLE
Improve dynamic title

### ISSUE THREAD

**Issue by benjaminbra** [benjaminbra/chat-socket#8]
Actualy, The dynamic title that show when there is à new message is not correctly working. 
If multiple messages are send, that add multiple (1)
But instead of this, it will be better if that show (1) then (2).... 

Second issue, the "alert" should be remove when the user is "active" on this window. And not when he click on the text.

**Comment by pierrerispal** [comment]
Yes i know, that was just a quick piece of code to show the principle

**Comment by benjaminbra** [comment]
This feature is done look at #11
